### PR TITLE
After regridding land prognostics, we adjust GHCNT to ensure deep soi…

### PR DESCRIPTION
**Pull request by smahanam**
**PURPOSE**
It was noted that the current regridding tool has a problem. If porosity of at an output tile is different to the porosity of the input tile that provided restart prognostics, there would be an inconsistency in deep soil temperature and ground heat content at the very beginning. Scale_Catch.F90 was modified to ensure deep soil temperature is preserved by scaling GHTCNT to match changing porosity.

### CODE REVIEW

**Comment by JustinPerket** [comment]
This a bug fix, testing in progress.

**Comment by smahanam** [comment]
Made the same modifications to Scale_CatchCN.F90

**Comment by JustinPerket** [comment]
This shows the effect of regridding from C360 (Old Land) to C180 (also Old Land) on the deepest soil temperature:
image


> **PURPOSE**
> It was noted that the current regridding tool has a problem. If porosity of an output tile is different to the porosity of the input tile that provided restart prognostics, there would be an inconsistency in deep soil temperature and ground heat content at the very beginning. Scale_Catch.F90 was modified to ensure deep soil temperature is preserved by scaling GHTCNT to match changing porosity.

In addition to porosity, this fix also takes into account ice fraction.

@gmao-rreichle  can correct me, but the land group is confident this is a correct fix, and the results look consistent with expectations. 

Perhaps this should be considered a hotfix

**Comment by gmao-rreichle** [comment]
I confirm that we tested the science of the fix off-line and were satisfied.

I don't understand what the "dimagi/required-labels" test is (executed by Matt?) and why it failed.  

FYI, this fix addresses the most important of three separate problems with regrid.  The other two are (i) the spatial mapping of source and target tiles and (ii) consideration of the WEMIN parameter in the regridding of snow depth.  These are being addressed.

**Comment by tclune** [comment]
The "required labels" are labels that categorize the pull request.   We added these so that requestors could distinguish zero-diff and nonzero-diff changes for the gatekeepers.  Different levels of testing are implied.

For this ticket the one that is in the way is the "Needs lead approval".    Has Bill approved this pull request as an issue?   (That process was announced several weeks ago to allow the GCM gatekeepers to manage the flood of changes that were coming in.)

**Comment by smahanam** [comment]
Sorry @tclune  ! No "issue" was open for this. The original pull request was in fact a "draft" for @JustinPerket  to check out and try. I can't figure out as to whether the request has been changed to a regular pull-request. 

In any case, @JustinPerket, lets open an issue for the 2 remaining updates that @gmao-rreichle mentioned. You can assign the me for the 2nd part which I am working on.

**Comment by JustinPerket** [comment]
> For this ticket the one that is in the way is the "Needs lead approval". Has Bill approved this pull request as an issue? (That process was announced several weeks ago to allow the GCM gatekeepers to manage the flood of changes that were coming in.)

I added the `Needs lead approval` tag so Bill would be sure to see this.The `feature/...` branch name is misnomer. It is more of a bug fix.  I checked with @sdrabenh about this, and it did not seem at the time that an issue needed to be created retroactively after @smahanam created the draft pull request, nor did it seem worthwhile to rename the branch to be `bugfix/...` or `hotfix/...`. This bug fix has also been discussed in several meetings last week, and in emails this week, so I thought that was sufficient. 


from @gmao-rreichle:  
>FYI, this fix addresses the most important of three separate problems with regrid. The other two are (i) the spatial mapping of source and target tiles and (ii) consideration of the WEMIN parameter in the regridding of snow depth. These are being addressed.

and @smahanam:
>In any case, @JustinPerket, lets open an issue for the 2 remaining updates that @gmao-rreichle mentioned. You can assign the me for the 2nd part which I am working on.

Agreed, I will create an issue for these remaining updates,

**Comment by JustinPerket** [comment]
build fails with:
```
root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/Raster/zip.c:4:10: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
```

presumably an easy fix

**Comment by smahanam** [comment]
> build fails with:
> 
> ```
> root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/Raster/zip.c:4:10: fatal error: zlib.h: No such file or directory
>  #include "zlib.h"
> ```
> 
> presumably an easy fix

@JustinPerket : This comment should move to the make_bcs PR ([#137](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/137))  
I did not experience this issue : I built on GEOSgcm "develop" and ran many cases without a problem.
Ask @mathomp4 or @atrayano

**Comment by JustinPerket** [comment]
Closing, since not yet merged, and  everything in this branch is duplicated with branches mentioned in https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/116 that are readying for a PR

**Pull request closed without merging**
