### PR TITLE
Update/geos 11.5.2

### PR DESCRIPTION
**Pull request by FlorianDeconinck**
Update the `dsl/develop` branch to the geos `v11.5.2` state, a.k.a `v2.5.2` for this comp.

WARNING: This will make the `OpenACC` port out-of-sync. Last sync'ed version is document in G002.1 of the SMT24-26 plan.

### CODE REVIEW

**Review by mathomp4 — APPROVED** [review]
Superapprove just to make things look clean. It isn't necessary I think for `dsl/develop`

**Comment by sanAkel** [comment]
@mathomp4 I don't know anything about `dsl/develop`. Maybe you can fill me in next time we chat ...

**Comment by FlorianDeconinck** [comment]
> @mathomp4 I don't know anything about `dsl/develop`. Maybe you can fill me in next time we chat ...

Allow me to reply, @sanAkel. `dsl/develop` is/will be the working branch for the Python-based DSL port of the physics parametrization my group will be attacking later this year. I'll be giving a talk to the GMAO at large sometime in April to go more in detail. 
Functionally, the Fortran code will be lightly touched, with a zero-diff, and most of the work will be moved to a new set of files stored in a `python` sub-directory.

**Comment by sanAkel** [comment]
Thanks @FlorianDeconinck.

> Allow me to reply, @sanAkel. `dsl/develop` is/will be the working branch for the Python-based DSL port of the physics parametrization my group will be attacking later this year. I'll be giving a talk to the GMAO at large sometime in April to go more in detail. Functionally, the Fortran code will be lightly touched, with a zero-diff, and most of the work will be moved to a new set of files stored in a `python` sub-directory.

Looking forward to `the GMAO at large sometime in April` meanwhile, would you be available/open to a _private_ conversation about it all sometime next week? If `yes`, would you please [email me](santha.akella@nasa.gov) a few convenient times. 🙏

**Pull request merged**
