### PR TITLE
Fix MOM_GEOS5Plug MAPL Timers

### PR DESCRIPTION
**Pull request by mathomp4**
@ehackert tried using MAPL timers and found a crash. The RUN2 timer was never
Added or turned off.

### CODE REVIEW

**Comment by mathomp4** [comment]
@yvikhlya My guess is the CVS tags would need the same fixes.

**Comment by yvikhlya** [comment]
> @yvikhlya My guess is the CVS tags would need the same fixes.

@mathomp4 @ehackert  Matt, thanks for tracking this down. I'll fix CVS tags.

**Comment by mathomp4** [comment]
> > @yvikhlya My guess is the CVS tags would need the same fixes.
> 
> @mathomp4 @ehackert Matt, thanks for tracking this down. I'll fix CVS tags.

That said, please test! I'm fairly confident this is the fix as the rest of GEOSocean seems balanced. Though GuestOcean is a bit wonky:
```
977:    call MAPL_TimerOn (STATE,"RUN"  )
978:    call MAPL_TimerOn (STATE,"TOTAL")
1213:          call MAPL_TimerOff(STATE,"TOTAL")
1214:          call MAPL_TimerOn (STATE,"--ModRun")
1279:          call MAPL_TimerOff(STATE,"--ModRun")
1280:          call MAPL_TimerOn (STATE,"TOTAL")
1354:    call MAPL_TimerOff(STATE,"TOTAL")
1355:    call MAPL_TimerOff(STATE,"RUN"  )
```
It turns off the TOTAL timer then does ModRun and then re-enables TOTAL. Not wrong, but it does exclude bits of code from the TOTAL timer.

**Comment by yvikhlya** [comment]
> > > @yvikhlya My guess is the CVS tags would need the same fixes.
> > 
> > 
> > @mathomp4 @ehackert Matt, thanks for tracking this down. I'll fix CVS tags.
> 
> That said, please test! I'm fairly confident this is the fix as the rest of GEOSocean seems balanced. Though GuestOcean is a bit wonky:
> 
> ```
> 977:    call MAPL_TimerOn (STATE,"RUN"  )
> 978:    call MAPL_TimerOn (STATE,"TOTAL")
> 1213:          call MAPL_TimerOff(STATE,"TOTAL")
> 1214:          call MAPL_TimerOn (STATE,"--ModRun")
> 1279:          call MAPL_TimerOff(STATE,"--ModRun")
> 1280:          call MAPL_TimerOn (STATE,"TOTAL")
> 1354:    call MAPL_TimerOff(STATE,"TOTAL")
> 1355:    call MAPL_TimerOff(STATE,"RUN"  )
> ```
> 
> It turns off the TOTAL timer then does ModRun and then re-enables TOTAL. Not wrong, but it does exclude bits of code from the TOTAL timer.

Could you fix this too on your branch? I'll do the same in CVS.

**Comment by mathomp4** [comment]
> > > > @yvikhlya My guess is the CVS tags would need the same fixes.
> > > 
> > > 
> > > @mathomp4 @ehackert Matt, thanks for tracking this down. I'll fix CVS tags.
> > 
> > 
> > That said, please test! I'm fairly confident this is the fix as the rest of GEOSocean seems balanced. Though GuestOcean is a bit wonky:
> > ```
> > 977:    call MAPL_TimerOn (STATE,"RUN"  )
> > 978:    call MAPL_TimerOn (STATE,"TOTAL")
> > 1213:          call MAPL_TimerOff(STATE,"TOTAL")
> > 1214:          call MAPL_TimerOn (STATE,"--ModRun")
> > 1279:          call MAPL_TimerOff(STATE,"--ModRun")
> > 1280:          call MAPL_TimerOn (STATE,"TOTAL")
> > 1354:    call MAPL_TimerOff(STATE,"TOTAL")
> > 1355:    call MAPL_TimerOff(STATE,"RUN"  )
> > ```
> > 
> > 
> > It turns off the TOTAL timer then does ModRun and then re-enables TOTAL. Not wrong, but it does exclude bits of code from the TOTAL timer.
> 
> ~Could you fix this too on your branch? I'll do the same in CVS.~ I take my words back. This could be done on purpose.

Whoops. I will undo!

**Comment by mathomp4** [comment]
> This should be on top of this merge
> 
> #293

It should be once merged. This is based on `develop` and #293 has been merged.

**Pull request merged**
