### PR TITLE
Bugfix/wjiang/dealloc mask

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
"mask" should be deallocated according to how it is allocated
The pointer "mask" is used  in the option of applying ldas increments to land model simulation ( ldas adas coupling application). The modification of this PR fixes the flawed code of deallocation  of "mask".  It has no impact to AGCM  when ldas increments application is  off.

### CODE REVIEW

**Comment by saraqzhang** [comment]
the fix in this PR  is tested  in adas coupled with ldas. 0-diff.

**Comment by gmao-rreichle** [comment]
@sdrabenh:
This PR fixes a bug in how a pointer is deallocated.
The bug was discovered when the GCM crashed within the weakly coupled ADAS-LDAS system.  (The vintage of the system that crashed is a bit unclear, but it seems to pre-date Ricardo's 5_29_3 suite of ADAS tags.)  
The changes are trivially 0-diff for the GCM because they are contained entirely within either C preprocessor directives for "debug" mode and within an if block for applying increments from the land analysis  [ `if(LDAS_INCR >0 )` ].  
@saraqzhang confirmed that the changes do fix the bug. 
Please let us know if you think that additional tests are needed, and @biljanaorescanin can take care of them. 
With any luck, the changes can go into the next planned GCM GC release.
Please let us know if you have any questions, thanks, - Rolf
cc: @biljanaorescanin, @weiyuan-jiang

**Review by gmao-rreichle — APPROVED** [review]

**Comment by mathomp4** [comment]
@gmao-rreichle Do you need this in a tag right away? Or at least in `develop` sooner rather than later?

**Comment by gmao-rreichle** [comment]
> @gmao-rreichle Do you need this in a tag right away? Or at least in `develop` sooner rather than later?

@mathomp4, @sdrabenh: This is not particularly urgent, as it "only" impacts the weakly coupled ADAS-LDAS system.  It would be helpful to have it on "develop" sooner rather than later.  Having said that, I just noticed that the automated "Build Tests / Build GEOSgcm (pull_request)" failed.  I have no clue what to make of that because "build-test" passed.  Any chance this has to do with the GEOSgcm merges of today?

**Comment by gmao-rreichle** [comment]
PS: My statement about the "failed" build test (Build GEOSgcm) is based on an email that I received from GitHub, see image below.  In the list of checks here in this PR, the build test (Build GEOSgcm) is listed as "skipped".  Sorry, but I'm rather confused about all this.
image

**Comment by mathomp4** [comment]
@gmao-rreichle It looks like everything worked. The GitHub action is skipped because you labeled it as trivial. Not sure why it would email a failure message!

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
