### PR TITLE
feature/donifan/mg3clean

### PR DESCRIPTION
**Pull request by dbarahon**
Cleaned up version of GEOS_MGB2_2M_InterfaceMod.F90. New parameterization for convective detrainment of number concentration. Fixes layout imprint for -O3 and COSP warning messages.

### CODE REVIEW

**Comment by mathomp4** [comment]
The weird run failures are most likely due to not being up-to-date with `develop`. @dbarahon Are you okay with my Updating your branch?

**Review by tclune — COMMENTED** [review]
cmake changes ok

**Comment by dbarahon** [comment]
> The weird run failures are most likely due to not being up-to-date with `develop`. @dbarahon Are you okay with my Updating your branch?

Yes, it is based on V11.5.0 so I'd expect no major impact

**Comment by dbarahon** [comment]
> @dbarahon @wmputman this PR passes my [0-diff tests](https://github.com/GEOS-ESM/GEOSgcm_GridComp/wiki/How-to-Run-GEOS-Zero-Diff-Tests) using the stock configuration (MGB2 off). However, when running with MGB2 it fails (1) stop/start regression and the (2) zero-increment replay test. Both of these tests need to pass to guarantee model reproducibility.

There must be some difference between your merge and mine. My sandbox passes both start-stop and layout test using MGVERSION: 3 . It can be found here: /gpfsm/dnb34/dbarahon/DEV/MG3_v1151_test/regress/

**Comment by dbarahon** [comment]
> @dbarahon @wmputman this PR passes my [0-diff tests](https://github.com/GEOS-ESM/GEOSgcm_GridComp/wiki/How-to-Run-GEOS-Zero-Diff-Tests) using the stock configuration (MGB2 off). However, when running with MGB2 it fails (1) stop/start regression and the (2) zero-increment replay test. Both of these tests need to pass to guarantee model reproducibility.

This must be fixed now with the latest commit. Please check whether it passes regression. It does for me even in debug mode.

**Pull request closed without merging**
