### PR TITLE
Restructuring under GEOSocean_GridComp

### PR DESCRIPTION
**Pull request by yvikhlya**
This PR addresses #447 and is contingent on https://github.com/GEOS-ESM/GEOSgcm/pull/317.

### CODE REVIEW

**Review by tclune — APPROVED** [review]
cmake changes ok

**Comment by mathomp4** [comment]
I'm adding @GEOS-ESM/gcm-gatekeepers (aka @sdrabenh) as this PR, as @yvikhlya says, is one of those "must be done at the same time as a GEOSgcm update" things. Want to make sure he knows about this so we can coordinate it.

**Comment by mathomp4** [comment]
Note: This will never pass CI here. 

It's a fun dependency issue, but the main thing is that by the time the CI system knows to checkout this branch, it's already done a `mepo clone` on the `main` of GEOSgcm. Thus, MOM5 and MOM6 are in the "wrong place" and so things go boom. You can see that the GEOSgcm CI in https://github.com/GEOS-ESM/GEOSgcm/pull/317 did build because it put MOM5 and MOM6 in the "right place". (Well, AWS failed but that's wonky at the best of times).

**Comment by yvikhlya** [comment]
Also note that I renamed GEOSocean_GridComp to GEOS_OceanGridComp. This way there is no need in "OVERRIDE" statement in CmakeLists.

**Review by sdrabenh — APPROVED** [review]

**Review by mathomp4 — APPROVED** [review]
Approving as superuser.

**Pull request merged**
