### PR TITLE
replace _RETURN(_SUCCESS)

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
This PR fixes the issue #483.

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
@tclune , do you know why it got fixed? Is anything wrong with "_RETURN(_SUCCESS)"?

**Comment by tclune** [comment]
Use git-blame to figure out who made the change.   I'm unaware of why the macros are not appropriate.

**Comment by weiyuan-jiang** [comment]
There is slightly difference. What I changed here is in a program, not a subroutine.

**Comment by gmao-rreichle** [comment]
Ok, thanks.  
Are you saying that neither `_RETURN(_SUCCESS)` nor `_RETURN(ESMF_SUCCESS)` will work in these small utility programs?
But both will work in subroutines that are part of the main program (associated with ESMF CAP?).
If that's the case, no further changes would be required, but it may still be sensible to change `_RETURN(_SUCCESS)` into `_RETURN(ESMF_SUCCESS)` for consistency across the GCM GridComp.  Or are these two flavors of "RETURN" somehow behaving differently?

**Comment by mathomp4** [comment]
I can confirm that this seems to fix #483. I'm going to see if I can make a push to this branch and fix the CI issue.

**Comment by mathomp4** [comment]
Adding a 0-diff label for GCM. Hopefully it works for @biljanaorescanin and the LDAS as well.

**Comment by mathomp4** [comment]
I have a label!! Graaaaah!

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
