### PR TITLE
Changes for CICECORE load balance

### PR DESCRIPTION
**Pull request by aoloso**
Changes were made to CICECORE in GEOS_CICE4ColumnPhysGridComp.F90 for load balancing.

### CODE REVIEW

**Review by zhaobin74 — APPROVED** [review]
This has been tested with zero-diff results.

**Review by sanAkel — CHANGES_REQUESTED** [review]
@aoloso would you please add some documentation (preferably inline, in GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/BufferPacking.h and in GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/BufferUnpacking.h) to describe what is: 
- purpose
- how it is being accomplished

If you do not like to add that in the code, please have it in the PR "comments" section.

Thank you!

**Comment by zhaobin74** [comment]
> I believe this requires [GEOS-ESM/MAPL#1650](https://github.com/GEOS-ESM/MAPL/pull/1650), right? If so, we should block this until a new MAPL is released.

@mathomp4, yes, it depends on that one. DNA label added.

**Comment by aoloso** [comment]
@sanAkel 
I have added comments to GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/[BufferPacking.h, BufferUnpacking.h] as you suggested.

**Comment by zhaobin74** [comment]
@aoloso, since LB_ON is zero-diff with LB_OFF but run faster, how about making ON as default in the code? Could you do that?

**Review by sanAkel — APPROVED** [review]
Thank you @aoloso

**Comment by sanAkel** [comment]
> @aoloso, since LB_ON is zero-diff with LB_OFF but runs faster, how about making ON as default in the code? Could you do that?

I support this request!

**Comment by aoloso** [comment]
@sanAkel I made it "TRUE" by default in this pull request. It was "FALSE" by default only for development when working off of "aogcm" branch.

**Comment by mathomp4** [comment]
Okay. MAPL 2.25 has been released:

https://github.com/GEOS-ESM/MAPL/releases/tag/v2.25.0

I suppose what is next is to have someone try this code with that tag. I'll make a PR to GEOSgcm to get MAPL 2.25 in there.

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
