### PR TITLE
remove c02, in conjunction with GMAO_Shared/pull/39

### PR DESCRIPTION
**Pull request by JustinPerket**
Parallel's https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/79, but for ```feature/ldas-surface``` instead of ```develop``` (merging the two isn't ready yet) After this, ```feature/ldas-surface``` should be merged into ```feature/for-SMAPtag```

### CODE REVIEW

**Comment by JustinPerket** [comment]
Note https://github.com/GEOS-ESM/GMAO_Shared/pull/39 needs to be merged first, and LDAS's externals would point to the new GMAO_Shared master

**Comment by mathomp4** [comment]
@JustinPerket getco2 has been officially moved.

**Comment by JustinPerket** [comment]
Thanks @mathomp4. To reiterate, LDAS will have to update Externals.cfg like GEOSgcm in github.com/GEOS-ESM/GEOSgcm/pull/57, and also add the FMS repo as mentioned in https://github.com/GEOS-ESM/GMAO_Shared/issues/40 like the External files in the ```GEOSgcm``` repo?

**Comment by JustinPerket** [comment]
builds successfully, otherwise no anticipated issues with https://github.com/GEOS-ESM/GEOSldas/pull/44  complete

**Comment by JustinPerket** [comment]
review by @GEOS-ESM/cmake-team,  and @weiyuan-jiang or @gmao-rreichle requested

**Pull request merged**
