### PR TITLE
Jperket/merge2ldas.0

### PR DESCRIPTION
**Pull request by JustinPerket**
branch from feature/ldas-surface, merged with develop

### CODE REVIEW

**Comment by JustinPerket** [comment]
@mathomp4 Need to override erroneous CircleCI build error check

**Comment by mathomp4** [comment]
> @mathomp4 Need to override erroneous CircleCI build error check

Well, for now it's not a blocking status check. It's an *annoying* status check in that it will throw fails until @pchakraborty fixes circle ci here, but it doesn't block. You can still press the "Merge pull request" button

**Comment by JustinPerket** [comment]
> > @mathomp4 Need to override erroneous CircleCI build error check
> 
> Well, for now it's not a blocking status check. It's an _annoying_ status check in that it will throw fails until @pchakraborty fixes circle ci here, but it doesn't block. You can still press the "Merge pull request" button

Noted.

**Comment by JustinPerket** [comment]
Note that the Surface/Shared/Raster changes are in the cvs tags `GEOSldas-m4-17_8beta2019-07-10` and the present `GEOSldas_m4-17_UNSTABLE`

**Comment by mathomp4** [comment]
Hmm. The CircleCI is back. I thought I'd fixed that...

**Pull request merged**
