### PR TITLE
Additional snow export variables

### PR DESCRIPTION
**Pull request by lcandre2**
This pull request is a work in progress (feature/lcandre2/newsnowexports). Do not approve.

The associated code modifications add new export variables from StieglitzSnow.F90 and catchment.F90 in order to examine the snow pack mass budget. The changes touch StieglitzSnow.F90, catchment.F90, and GEOS_CatchGridComp.F90 and include the export of 4 new variables:
mltwtr: total meltwater production rate (1D; kg m-2 s-1)
pre: liquid water flow from snow base (1D; kg m-2 s-1)
fices: layer frozen fraction (2D, but exports are 1D FICES[1-3] following WESN, unitless)
excs: frozen part of water content from densification excess (2D, but exports are 1D, EXCS[1-3]; kg m-2 s-1).

TO DO (associated changes may not be 0-diff):
-- check operations 
-- code clean up, including export renaming
--check on where excs is applied within catchment and how it is partitioned
--revisit the generation of excs. Currently, it is calculated at each time step when snow density exceeds 500 kg m-3. Values are not insignificant (see figure below).

@rdkoster @gmao-rreichle @gmao-qliu @amfox37 

excs13

### CODE REVIEW

**Comment by sanAkel** [comment]
@lcandre2 Would be _nice_ if you remove commented initials (`lca`); these changes can be [tracked using other means such as this](https://git-scm.com/docs/git-blame). Thanks!

**Comment by gmao-rreichle** [comment]
> @lcandre2 Would be _nice_ if you remove commented initials (`lca`); these changes can be [tracked using other means such as this](https://git-scm.com/docs/git-blame). Thanks!

Yes, but git-blame only works only until git is replaced by whatever version control tool comes next.  Changes made during the CVS era are now all just one giant "initial commit".  Also, while git-blame is great for the most recent changes, tracking down older edits can be a pain.  IMHO, adding initials and the like is mostly a preference.  There are pros and cons.

**Comment by lcandre2** [comment]
> @lcandre2 Would be _nice_ if you remove commented initials (`lca`); these changes can be [tracked using other means such as this](https://git-scm.com/docs/git-blame). Thanks!

Totally fair @sanAkel, but this isn't final, and the comments allow me to easily search for variables that were originally given non-descriptive names like 'pre'. I'll remove references to my additions when the pull request is no longer a draft!

**Comment by mathomp4** [comment]
@lcandre2 Something is very...odd with branch. It's like you changed the permissions of everything and committed that somehow. If you look at:

https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/809/files

you'll see a lot of files that were 644 are now 755 and that's the only difference.

**Comment by gmao-rreichle** [comment]
> you'll see a lot of files that were 644 are now 755 and that's the only difference.

Thanks, @mathomp4, for pointing this out.  I hadn't looked at the branch yet.  I'll fix it when I get to it.  It's not anywhere near approval and merging, so not urgent.

**Comment by gmao-rreichle** [comment]
Closing PR because of issues with changes in file permissions.  Replaced by #814

**Pull request closed without merging**
