### PR TITLE
Feature/ltakacs/r21c observed precip

### PR DESCRIPTION
**Pull request by lltakacs**

### CODE REVIEW

**Comment by sdrabenh** [comment]
Requires companions PR [#169](https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/169)

**Review by gmao-rreichle — DISMISSED** [review]
Looks ok to me.  One question, though: Should we change the default latitude band for tapering of precip corrections?  With the IMERG-based corrections in R21C, the latitude band should be 50-60 N/S (rather than 42.5-62.5 N/S as in M-2).  Below is a link to the MAPL_GetResource() hard-coded defaults.  
The same numbers are probably also in a GCM rc file somewhere. 
cc: @gmao-qliu 

Precip corr Tech Memo: https://gmao.gsfc.nasa.gov/pubs/docs/Reichle1344.pdf

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/3a337d43f120cb81e2f60456e85b779a04f7336f/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90#L5957

**Comment by lltakacs** [comment]
> Looks ok to me. One question, though: Should we change the default latitude band for tapering of precip corrections? With the IMERG-based corrections in R21C, the latitude band should be 50-60 N/S (rather than 42.5-62.5 N/S as in M-2). Below is a link to the MAPL_GetResource() hard-coded defaults. The same numbers are probably also in a GCM rc file somewhere. cc: @gmao-qliu
> 
> Precip corr Tech Memo: https://gmao.gsfc.nasa.gov/pubs/docs/Reichle1344.pdf
> 
> https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/3a337d43f120cb81e2f60456e85b779a04f7336f/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90#L5957

Yes, Rolf, that is a good idea.  I will try to merge that into my feature branch.

**Review by sanAkel — COMMENTED** [review]
Does this impact:
1. Coupled model configuration? I can't tell!
2. What is the difference (from what I get now) over ocean (and sea ice; even in atmosphere-only mode)?
     - liquid precip
     - frozen precip
     
If anything !=0 why?

**Comment by lltakacs** [comment]
> Does this impact:
> 
>     1. Coupled model configuration? I can't tell!
> 
>     2. What is the difference (from what I get now) over ocean (and sea ice; even in atmosphere-only mode)?
>        
>        * liquid precip
>        * frozen precip
> 
> 
> If any difference !=0 why?

If you are NOT using an Observed Precip file, this code is zero-diff.  Otherwise, the code now uses a MAPL-2 interface to read the Observed Precip file.  The method of partitioning the observed precip has not changed.  For the case of R21C, the Observed Precip file is associated with IMERG data and is defined on the cubed-sphere.  The default values used for the latitudinal tapering have changed from (42.5-62.5) to (50-60).  The MAPL-2 interface may give round-off differences if reading the Lat/Lon MERRA-2 observed precip file.  I did not check this.

**Comment by mathomp4** [comment]
Random question: is this a configuration I should be running in my nightly tests for any reason? Or is it the sort of thing where it works or it doesn't rather than 'might change nightly'?

**Comment by sdrabenh** [comment]
@mathomp4 from an AGCM standpoint, I don't think this needs to be a nightly test at this point. The default is off.

**Comment by zhaobin74** [comment]
Doesn't affect landice. Good to go.

**Comment by sanAkel** [comment]
>> If you are NOT using an Observed Precip file, this code is zero-diff. 

Thank you @lltakacs, that's great!

Based on what @sdrabenh says:
>@mathomp4 from an AGCM standpoint, I don't think this needs to be a nightly test at this point. **The default is off.**

There is an _option_ 👍 

Thanks!

**Review by sanAkel — APPROVED** [review]

**Comment by sanAkel** [comment]
> Doesn't affect landice. Good to go.

@zhaobin74 then please hit "approve" 😄

**Review by zhaobin74 — APPROVED** [review]

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
