### PR TITLE
Feature/mfmehari/data atm bug fix

### PR DESCRIPTION
**Pull request by mfmehari**
A bug, that was making DataAtm to run with a certain number of processors but not with other numbers, has been fixed. 
An update in GCM GC that allows DataAtm to run.
An ExtData yaml file has been added to the DataAtm GC directory.
A zero diff PR.

### CODE REVIEW

**Comment by sdrabenh** [comment]
@mfmehari just I tested this PR + https://github.com/GEOS-ESM/GEOSgcm_App/pull/650 and the model crashes during initialization:

pe=00012 FAIL at line=00075    ExtDataConfig.F90                    \<could not find: CORE_NYF_Data_AtmForcings_ExtData.yaml> 
pe=00012 FAIL at line=00084    ExtDataConfig.F90                    <status=1>
pe=00012 FAIL at line=00051    ExtDataOldTypesCreator.F90  <status=1>
pe=00012 FAIL at line=00291    ExtDataGridCompNG.F90       <status=1>

The file exists in the source directory:
`src/Components/@GEOSgcm_GridComp/GEOSdataatm_GridComp/CORE_NYF_Data_AtmForcings_ExtData.yaml`
but not in the install directory. Thus, is is not copied to the exp directory either. Please fix these PRs and retest from a clean build to ensure they run. Also, please verify everything is 0-diff/disabled by default.

**Comment by mathomp4** [comment]
@mfmehari You'll need to add something like:
```cmake
install(FILES CORE_NYF_Data_AtmForcings_ExtData.yaml DESTINATION etc)
```
to the `CMakeLists.txt` to install it.

**Comment by mfmehari** [comment]
@mathomp4 thank you very much!
I was to ask you ...

**Comment by mfmehari** [comment]
@sdrabenh the PRs are fixed, instructions to install the .yaml file have been added to CMakeLists.txt.
 Rerun from a clean build.
It is a 0 diff fix.

**Review by sdrabenh — APPROVED** [review]

**Review by mathomp4 — APPROVED** [review]

**Comment by mfmehari** [comment]
@sdrabenh @mathomp4 @bena-nasa Thank you all!

**Pull request merged**
