### PR TITLE
Modified RUN1 to load balance

### PR DESCRIPTION
**Pull request by aoloso**
Subroutine RUN1  of GEOS_CICE4ColumnPhysGridComp is modified to for load balancing similar to what was previously done for subroutine CICECORE in subroutine RUN2.

### CODE REVIEW

**Comment by sanAkel** [comment]
FWIW, these changes provide a _slight_ speed up:

All runs are for 1 month with `cas`.
 
Ocean Model | NCPUS | mean wallclock time before update (number of simulations) | mean wallclock time after update (number of simulations)  |
MOM5            |   1440  |  145 min  (1) | 136 min (2) |
MOM6            |   1440  |  193 min  (3) | 196 min (1) |  **there was a variability of > 20 min in my runs before update.

**Review by sanAkel — APPROVED** [review]
Thanks for tidying! (reviewing on behalf of the @GEOS-ESM/ocean-team)

**Review by zhaobin74 — COMMENTED** [review]
@aoloso, thanks for this PR. But I see you also brought in changes to other components not related to CICE4 load balance. I am not able to review all of them.

**Review by zhaobin74 — APPROVED** [review]
All sea ice components are fine. Approve.

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
