### PR TITLE
R21C: remove filling of WET1 (a.k.a. GWETTOP) with 1s over non-land

### PR DESCRIPTION
**Pull request by gmao-rreichle**
As in #974 but for R21C.

@biljanaorescanin @sdrabenh @mathomp4 @bena-nasa @atrayano @rdkoster @elakkraoui

### CODE REVIEW

**Review by lcandre2 — APPROVED** [review]

**Comment by mathomp4** [comment]
NOTE: I've blocked and drafted this for now as the change is non-zero-diff in `develop` so I imagine it is the same in M21C. See https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/974#issuecomment-2273389994 for more details

**Comment by mathomp4** [comment]
@gmao-rreichle et al I think what is here now should be good. I made a new `WET1_FOR_CHEM` export and pass that to chemistry. Meanwhile, the `WET1` export is now UNDEF over the ocean.

Note: My guess is the "right" thing is to only have one `WET1` and fix up GOCART, but for now, this works.

**Comment by gmao-rreichle** [comment]
Thanks, @mathomp4 !  I changed the LONG_NAMES of WET1 and WET1_FOR_CHEM to what we want them to be in M21C.  (Unfortunately, the "develop" branch is still behind on this aspect.)  Looks good to me now.

**Comment by mathomp4** [comment]
> Thanks, @mathomp4 ! I changed the LONG_NAMES of WET1 and WET1_FOR_CHEM to what we want them to be in M21C. (Unfortunately, the "develop" branch is still behind on this aspect.) Looks good to me now.

Make any changes you like! Indeed, feel free to change or add comments as needed!

**Review by elakkraoui — APPROVED** [review]

**Review by biljanaorescanin — APPROVED** [review]

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
