### PR TITLE
remove extra variables that are in ice and water restart

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
This PR address issue #621 . @zhaobin74 , This is a non-zero diff PR. I am not familiar with the ice and water restart. Would you please review and verify this PR?

### CODE REVIEW

**Comment by zhaobin74** [comment]
I am not sure what is the best way to test this. Could @mathomp4 do this just like he did for other cases?

**Comment by weiyuan-jiang** [comment]
There is no way for us to "test". I think the one who knows the science need to open the files and see what is inside

**Comment by zhaobin74** [comment]
> There is no way for us to "test". I think the one who knows the science need to open the files and see what is inside
Do you have a set of files I can look at? Or do you want me to run this?

**Comment by weiyuan-jiang** [comment]
> 

I don't.  The testing cases are not using split...

**Comment by weiyuan-jiang** [comment]
This PR depends on the PR in MAPL https://github.com/GEOS-ESM/MAPL/pull/1644

**Comment by zhaobin74** [comment]
The updated SlatIntSplitter now produces the proper set of fields in the restarts for openwater and seaicethermo. PR can be merged. Thanks.

**Comment by weiyuan-jiang** [comment]
@mathomp4 which version of MAPL  the test builds with ?

**Comment by mathomp4** [comment]
> @mathomp4 which version of MAPL the test builds with ?

I think the test will still use MAPL 2.23 or older until @sdrabenh can test and pull in https://github.com/GEOS-ESM/GEOSgcm/pull/452

**Comment by sdrabenh** [comment]
Adding 0-diff label if not running `SaltIntSplitter` and non-0-diff label if one does (starting with `saltwater_internal_rst`).

**Comment by mathomp4** [comment]
> Adding 0-diff label if not running `SaltIntSplitter` and non-0-diff label if one does (starting with `saltwater_internal_rst`). MAPL 2.25 is now in GEOSgcm main.

And it looks like the CI is happy now! 🎉

**Comment by sdrabenh** [comment]
@gmao-rreichle are you okay with this PR even though it doesn't touch land? We need a member of `GEOS-ESM/surface-preproc-team` to approve

**Review by gmao-rreichle — APPROVED** [review]
Approving for the @GEOS-ESM/surface-preproc-team per @sdrabenh's request.
I trust that everything is ok and the ocean and ice experts are ok with merging the PR.

**Comment by sdrabenh** [comment]
> Approving for the @GEOS-ESM/surface-preproc-team per @sdrabenh's request.

Thanks!

**Pull request merged**
