### PR TITLE
MOM6 in GEOS - Part 1

### PR DESCRIPTION
**Pull request by aerorahul**
This PR enables the checkout of MOM6 source code and stages it with existing MOM5.
It also adds a plug.  The plug and the source code are not used, as a result, no change in output (compile time or runtime) is expected.  `GuestOcean_GridComp.F90` is left untouched.

A second PR will make use of this new code. Changes will be limited to the `GuestOcean_Grid Comp.F90` and accompanying `CMakeLists.txt`

This is ongoing work related to issue GEOS-ESM/GEOSgcm_GridComp#70

Change-Id: I75bf29d16e626f68d4bafadb3ba3ecac909cd9ff

### CODE REVIEW

**Comment by mathomp4** [comment]
@aerorahul I assume `branch = geos` is just until MOM6 is finalized and working?

**Comment by aerorahul** [comment]
> @aerorahul I assume `branch = geos` is just until MOM6 is finalized and working?

@mathomp4 This is the branch of MOM6 on our fork.  Are you thinking of creating something along the lines of `geos/master` , `geos/develop`. In which case this will eventually become `geos/develop` or a tag when we have active MOM6 development.

This is not to be confused with the FMS branch `geos` which contains the latest changes from `xanadu` tags.

**Comment by mathomp4** [comment]
> > @aerorahul I assume `branch = geos` is just until MOM6 is finalized and working?
> 
> @mathomp4 This is the branch of MOM6 on our fork. Are you thinking of creating something along the lines of `geos/master` , `geos/develop`. In which case this will eventually become `geos/develop` or a tag when we have active MOM6 development.
> 
> This is not to be confused with the FMS branch `geos` which contains the latest changes from `xanadu` tags.

@aerorahul I just wanted to make sure that the branch is what you wanted rather than a fixed tag. I'm guessing you have development ongoing and will provide a tag the next time `develop` merges into `master`?

**Comment by aerorahul** [comment]
> > > @aerorahul I assume `branch = geos` is just until MOM6 is finalized and working?
> > 
> > 
> > @mathomp4 This is the branch of MOM6 on our fork. Are you thinking of creating something along the lines of `geos/master` , `geos/develop`. In which case this will eventually become `geos/develop` or a tag when we have active MOM6 development.
> > This is not to be confused with the FMS branch `geos` which contains the latest changes from `xanadu` tags.
> 
> @aerorahul I just wanted to make sure that the branch is what you wanted rather than a fixed tag. I'm guessing you have development ongoing and will provide a tag the next time `develop` merges into `master`?

yes. That will be fine for now.  Once we can actually exercise this option, we can start tagging.

**Comment by mathomp4** [comment]
Okay. Give me some more time. I might have to do some fun to make this generally supported. I think I might have to rebuild bits of Baselibs because of the use of `https` URLs in the submodules inside of MOM6. Hmm...

**Comment by mathomp4** [comment]
Hmm. I might be able to escape this with a few lines of change in `@env` changing order of modules. Unexpected, but possible.

**Comment by aerorahul** [comment]
@mathomp4 Can't we just put an Externals.cfg in the MOM6 fork and remove the submodules? Seems easy that way.
One of the repo is kdtree and that is not changing or going away.

**Comment by mathomp4** [comment]
@aerorahul This is something that will happen at some point anyway, may as well figure it out now. The problem is that if you load `g5_modules` and then try to run `checkout_externals` you get a lot of:
```
Checking out externals: geoschem_gridcomp, mom6, ERROR:root:Command '[u'git', u'submodule', u'update', u'--init', u'--recursive']' returned non-zero exit status 1
ERROR:root:Failed with output:
    Submodule 'pkg/CVMix-src' (https://github.com/CVMix/CVMix-src.git) registered for path 'pkg/CVMix-src'
    Submodule 'pkg/MOM6_DA_hooks' (https://github.com/MJHarrison-GFDL/MOM6_DA_hooks.git) registered for path 'pkg/MOM6_DA_hooks'
    Submodule 'pkg/geoKdTree' (https://github.com/travissluka/geoKdTree.git) registered for path 'pkg/geoKdTree'
    Cloning into '/gpfsm/dswdev/mathomp4/Models/CURLTEST-GEOSgcm-develop-with-MOM6part1/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/@mom6/pkg/CVMix-src'...
    fatal: unable to access 'https://github.com/CVMix/CVMix-src.git/': Protocol "https" not supported or disabled in libcurl
    fatal: clone of 'https://github.com/CVMix/CVMix-src.git' into submodule path '/gpfsm/dswdev/mathomp4/Models/CURLTEST-GEOSgcm-develop-with-MOM6part1/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/@mom6/pkg/CVMix-src' failed
    Failed to clone 'pkg/CVMix-src'. Retry scheduled
    Cloning into '/gpfsm/dswdev/mathomp4/Models/CURLTEST-GEOSgcm-develop-with-MOM6part1/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/@mom6/pkg/MOM6_DA_hooks'...
    fatal: unable to access 'https://github.com/MJHarrison-GFDL/MOM6_DA_hooks.git/': Protocol "https" not supported or disabled in libcurl
```
It looks like this is due to the libcurl in SIVO-PyD and the stupid old version of OpenSSL on discover SLES 11. Without `g5_modules` loaded:
```
(1008)(master) $ ldd /gpfsm/dulocal/sles11/other/SLES11.3/git/2.21.0/libexec/git-core/git-http-push | grep curl
	libcurl.so.4 => /gpfsm/dulocal/sles11/other/SLES11.3/git/2.21.0/lib/libcurl.so.4 (0x00002aaaaaaad000)
```
with `g5_modules` loaded:
```
❯ ldd /gpfsm/dulocal/sles11/other/SLES11.3/git/2.21.0/libexec/git-core/git-http-push | grep curl
	libcurl.so.4 => /usr/local/other/SLES11.3/SIVO-PyD/1.25.1_gcc6.3_mkl17.0.4.196/lib/libcurl.so.4 (0x00002aaaaaaae000)
```
But, I think we can avoid this simply by loading GEOSenv *after* SIVO-PyD so that the `LD_LIBRARY_PATH` is uncontaminated.

**Comment by mathomp4** [comment]
@aerorahul You should have a pull request into your `feature/mom6-struct` branch on `GEOSgcm` where I've advanced `ESMA_env`to 1.3.3 in `Develop.cfg`. That, I think, solves the issue simply. If you agree with the change, merge and let me know and I'll do another test to be sure.

**Comment by aerorahul** [comment]
Sorry this got closed when I deleted the branch `feature/mom6-struct`.
Currently, `feature/mom6-struct` and `feature/mom6-opt` are both same.
I will delete `feature/mom6-opt`.
@yvikhlya please use `feature/mom6-struct` for your development/integration of MOM6 advance in GEOS.

**Comment by aerorahul** [comment]
@mathomp4 Once [FMS dependency](https://github.com/geos-esm/gmao_shared/issues/14) is satisfied, this branch `feature/mom6-struct` will need to be brought up to date with the latest develop.  I don't expect any conflicts, since this work is completely new w.r.t. existing code base.

**Pull request closed without merging**
