### PR TITLE
Feature/aogcm

### PR DESCRIPTION
**Pull request by dbarahon**
Critical fix in cldwat2m_micro.F90

### CODE REVIEW

**Review by tclune — APPROVED** [review]
cmake changes are ok

**Comment by mathomp4** [comment]
@dbarahon This seems like a pretty big commit for a critical fix. It seems to change...everything in Moist.

**Comment by yvikhlya** [comment]
@dbarahon We don't actually want to merge this into develop, please close this PR.

**Comment by dbarahon** [comment]
OK, it was supposed to be one line only.

I got this wrong, definitely. Not sure where to “request” this fix. It is suppose to go on top of feature/aogcm only. Nevermind, I am closing it.

TBH, creating a pull request is an almost mystical ritual.

Donifan



From: Matthew Thompson ***@***.***>
Reply-To: GEOS-ESM/GEOSgcm_GridComp ***@***.***>
Date: Friday, September 17, 2021 at 1:09 PM
To: GEOS-ESM/GEOSgcm_GridComp ***@***.***>
Cc: "Barahona, Donifan (GSFC-6101)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSgcm_GridComp] Feature/aogcm (#453)


@dbarahon<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbarahon&data=04%7C01%7Cdonifan.o.barahona%40nasa.gov%7C9c5ae8a30c9a47f5796908d979fde1d6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637674953596009730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HDOHI%2BMmWzPhFoEW1lCP2XXOLTX6uhmAtenHQrqY%2FIQ%3D&reserved=0> This seems like a pretty big commit for a critical fix. It seems to change...everything in Moist.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOSgcm_GridComp%2Fpull%2F453%23issuecomment-921951285&data=04%7C01%7Cdonifan.o.barahona%40nasa.gov%7C9c5ae8a30c9a47f5796908d979fde1d6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637674953596009730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hwbPvSA%2F6eDAj2fpdwNnNQiugsnIStldRhKcXJQ6uWY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAM3UCERJFKJPPRRXQCXRPILUCNY3VANCNFSM5EH6RHGA&data=04%7C01%7Cdonifan.o.barahona%40nasa.gov%7C9c5ae8a30c9a47f5796908d979fde1d6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637674953596019695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q8%2Fqgsf3AlBG4RJTRSSN3t29eKtF6ZpZzPRlEf6G4QQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdonifan.o.barahona%40nasa.gov%7C9c5ae8a30c9a47f5796908d979fde1d6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637674953596019695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vbp4iXwX9MhTskqgYyJUm6yqY0l30RirA8hd%2BtSFzwc%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdonifan.o.barahona%40nasa.gov%7C9c5ae8a30c9a47f5796908d979fde1d6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637674953596029645%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nuPalRtKHU2cES9W9LqVo3OCbWz%2FG2atA%2F9h7DY5xXk%3D&reserved=0>.

**Pull request closed without merging**
