### PR TITLE
Fixes #27 - register grids from AdvCore

### LINKED ISSUE #27: AdvCore_GridComp does not register its grids
AdvCore needs to register its grid like DynCore does

### PR DESCRIPTION
**Pull request by kgerheiser**
Move register_grid_and_regridders to its own module to avoid duplication and call it from AdvCore

### CODE REVIEW

**Comment by mathomp4** [comment]
I think this is indeed a @bena-nasa request. :smile:

**Comment by bena-nasa** [comment]
@sdrabenh This should be a trivial zero-diff change.

**Comment by sdrabenh** [comment]
@kgerheiser please double check this code again. Maybe I am doing something incorrect, but every time I run your executable it seg faults.

**Comment by tclune** [comment]
@sdrabenh Failures for you are odd given that this code only affects the advect core which I don't think is exercised in your usual tests.    But I agree first step is for @kgerheiser to double check a standard build on his end.  If that still works for him the SI team will look deeper into the issue.

**Comment by sdrabenh** [comment]
I agree it is odd. I built this two different times and could never run it without seg fault. I have not had this issue with any other pull requests yet.

**Comment by tclune** [comment]
Note: Whoever submits the pull request for this should also fix the various declarations (e.g., temp2d) that are declared with KIND=4.   This is not standard conforming.   E.g., with the  NAG Fortran compiler  KIND=1 is 32 bit real with the default settings and can be something rather weird with more aggressive debug flags.

**Comment by kgerheiser** [comment]
I found the problem and fixed it. Somehow I missed part of the register_grid_and_regridders subroutine where it added the prototype to the GridManager.

**Comment by sdrabenh** [comment]
@kgerheiser has the push been updated? I see the same 4 files but can't tell if your most recent changes are included. Also, can you please verify this is zero diff?

**Comment by tclune** [comment]
@sdrabenh It can be a bit subtle to see the subsequent changes during an ongoing PR.   But you should see two "View Changes" boxes on the RHS of the thread above.     The second one was just before Kyle posted his claim of fixing the problem.   That one has changes in only one file.

**Comment by tclune** [comment]
@kgerheiser   Now that we finally merged the change that puts the dycore into its own repository, you are going to need to redo this PR in 

https://github.com/GEOS-ESM/FVdycoreCubed_GridComp

or maybe even in 

https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere

depending on where the files are.

Sorry about that.   (Note that I did bring in your other hotfix though, so we should be out-of-the-woods on further complications.)

**Pull request closed without merging**
