### PR TITLE
disable CatchmentCNCLM45 (LSM_CHOICE=3)

### PR DESCRIPTION
**Pull request by gmao-jkolassa**
This PR disables the use of CatchmentCNCLM45 (LSM_CHOICE=3) and supersedes #898.

This particular model version has lots of science issues, and NCAR discourages the use of CLM45, from which the carbon and nitrogen cycle components of CatchmentCNCLM45 are borrowed.

The PR removes the LAND_PARAMS=CN_CLM45 option from the surface resource file and removes the LSM_CHOICE=3 option in select case/if blocks to make sure  the code does not run with this model version.  A more thorough source code cleanup will be needed at a later time. 

Related PRs:

https://github.com/GEOS-ESM/GEOSldas/pull/707 

This PR is zero-diff. 

See also planned cleanup of source code https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/907 

cc: @gmao-rreichle , @biljanaorescanin

### CODE REVIEW

**Review by gmao-rreichle — APPROVED** [review]
PR only comments out a few if blocks for CatchmentCNCLM45.  I'd call it trivially 0-diff.  CI build and runs work.  @sdrabenh, please let us know if you need more formal testing.

**Comment by sanAkel** [comment]
why don't you just remove this choice?

**Comment by gmao-rreichle** [comment]
> Instead of commenting it, why don't you just remove this choice?

A more thorough code cleanup will be done when we replace CatchCNCLM4.5 with CatchCNCLM5.1.  This is a quick safety to make sure nobody can bypass the corresponding changes in setup.

**Comment by gmao-rreichle** [comment]
> @gmao-rreichle in that case, we'll need an issue that goes with this PR. The issue I suggest would have: `A more thorough code cleanup will be done`. Does that make sense?

@sanAkel : Done.

**Review by sanAkel — APPROVED** [review]

**Review by lcandre2 — COMMENTED** [review]
Fine by me.

**Review by sdrabenh — APPROVED** [review]

**Comment by sdrabenh** [comment]
Fine with me too

**Pull request merged**
