### PR TITLE
mv getids.H to mk_shared.F90 under land shared

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
mv mk_LDASsaRestarts.F90 to GEOSldas App

### CODE REVIEW

**Comment by smahanam** [comment]
GEOSland_GridComp/Shared is to keep shared modules for land surface models (CATCH and CATCHCN)
mk_restarts directory contains all regridding tools for land, ice, lake, saltwater and all kind of surface tiles. Those routines in getids.H are part of regridding. So I don't think GEOSland_GridComp/Shared is for the place for new module mk_shared.F90

Perhaps, we can move back mk_shared.F90 back to mk_restarts and  just rename to getids.F90.

My 2cs, other than that your changes to getids.H look good to me.

**Comment by weiyuan-jiang** [comment]
That means we need to generate a module or a lib out of the mk_restarts. That is something I want to avoid

**Comment by smahanam** [comment]
I understood your point, but ....sorry,  I still can't agree.
I'll leave it to you, anyways.

**Comment by gmao-rreichle** [comment]
I don't quite understand why we shouldn't have a module or lib in ./mk_restarts.  Don't we have executables there?  If there's a good reason to avoid putting the new module into mk_restarts, shouldn't it live further  up in Surface/Shared?  Land/Shared is somewhere inbetween and not a good fit.

**Comment by smahanam** [comment]
If @weiyuan-jiang really wants to avoid adding a new library, Surface/Shared more sense is more sense to me.

**Comment by weiyuan-jiang** [comment]
Then maybe it is good time to re-org the codes. I have no idea why mk_restars is under catch_gridcomp  where there are ice, water , catchcn, lake,....

**Comment by smahanam** [comment]
If you really want to think, the whole mk_restarts directory should move out of GEOScatch_GrdiComp and move to Surface/Shared
like wehave Surface/Shared/Raster for surface  BCs

**Comment by gmao-rreichle** [comment]
I have no idea why mk_restarts lives in Catch, but presumably there are Catch-specific subroutines in the package.   Moving everything to Surface isn't a great idea, necessarily.  Presumably, each Component (Catch, Veg, etc) should have some component-specific code to generate restarts, and everything should be tied together by some programs in Surface/Shared that deal primarily with location (geographic) info.   
If you are serious about reorganizing, I recommend talking with Larry first.  He may have additional helpful insights.

**Comment by smahanam** [comment]
Yes talk to @atrayano, @lltakacs , @gmao-jstassi  first
As I understand, moving mk_restarts to Surface/Shared is the right thing.

**Comment by weiyuan-jiang** [comment]
The file name is renamed to mk_restarts_shared.F90 that says itself

**Comment by gmao-rreichle** [comment]
Closing this pull request for now until we have got clearance from Scott et al to proceed.

**Comment by smahanam** [comment]
@weiyuan

**Pull request closed without merging**
