### PR TITLE
barebones LDAS functionality 

### PR DESCRIPTION
**Pull request by JustinPerket**
**This PR is needed quickly to**
- **get LDAS to be able to start using the develop branch**
- **get a semantic version tag for SMAP soon** 

## Description
This is the bare minimum to get LDAS working with the develop branch of GEOSgcm_GC. Science features that LDAS has and the AGCM lacks have been **stripped out**. This includes:

- Land surf increment code.
- CatchCN updates
- Irrigation functionality 
- River routing updates

The differences that **do remain** to be merged are:

- ensemble id width for LDAS
- added co2 file for CatchCN support
- bug fix that only affects New Land when snow impurity model is active (which it usually isn't)

## Testing
tested to be 0-diff with LDAS system test:
```/discover/nobackup/jperket/SystemTests/logs/LDAS/2019-09-11/log.14:42:09```

tested to be 0-diff for both new land and old land in AGCM with AMIP, replay, and 0-increment replay. Regressions tests also pass. Test directories are:
```
/discover/nobackup/projects/gmao/g6dev/jperket/tests/JPTest_Test_NL_2019-09-11
/discover/nobackup/projects/gmao/g6dev/jperket/tests/JPTest_Test_OL_2019-09-11
```

### CODE REVIEW

**Comment by JustinPerket** [comment]
3323f2a should make this good to go. I should restart first though

**Comment by JustinPerket** [comment]
@lltakacs  @sdrabenh AMIP test was rerun and restarts were 0-diff

Considering the changes since the last test (3323f2a, 376f24e) were structural, are we good for you to verify with the remainder the tests?

**Comment by sdrabenh** [comment]
Ok, I can run the rest of the zero-diff tests.

**Comment by sdrabenh** [comment]
@JustinPerket it is merged now

**Comment by JustinPerket** [comment]
woohoo! thanks @sdrabenh

**Pull request merged**
