### PR TITLE
correct LONG_NAME for absorbed and emitted longwave flux in Surface

### PR DESCRIPTION
**Pull request by gmao-rreichle**
Longwave radiation fluxes in Surface, Catch[CN], and Lake include only the absorbed and emitted portions of the fluxes and exclude the reflected portion.  Variables are confusingly labeled "downwelling" and "upwelling/outgoing" throughout Surface, Catch[CN], and Lake.  This PR fixes the corresponding LONG_NAME attributes of the Export and Import specs.  Fortran variable names in the source code are not changed.

I did not look at the Landice and Saltwater GridComps.   The @GEOS-ESM/landice-team and @GEOS-ESM/ocean-team may want to check their GridComps.  If changes are needed, feel free to commit directly onto my branch, no need for a separate PR.

@gmao-jkolassa, please make sure these changes are copied into your CatchCTSMv5.1 GridComp branch.

The PR should be trivially 0-diff.  Moreover, none of the impacted Exports are used in the standard HISTORY templates of the [GEOSgcm_App](https://github.com/GEOS-ESM/GEOSgcm_App), so the PR should have no impact on any of the current GEOS data products.

**Net** fluxes are not impacted because:

  LW_NET = LW_UP - LW_DOWN = LW_ABSORBED - LW_EMITTED

To obtain upwelling longwave radiation from standard HISTORY output, use:

  LW_UP =  LW_DOWN - LW_NET = ( LW_ABSORBED / EMIS ) - LW_NET    

cc: @rdkoster @weiyuan-jiang @biljanaorescanin @lcandre2 @rcullath @dr0cloud @rlucches

### CODE REVIEW

**Review by yvikhlya — DISMISSED** [review]

**Comment by zhaobin74** [comment]
I have committed in Landice,  Saltwater,  Openwater, SimpleSeaice and CICE4ColumnPhys gridcomps with the same LONGNAME corrections.

**Comment by lcandre2** [comment]
> I have committed in Landice, Saltwater, Openwater, SimpleSeaice and CICE4ColumnPhys gridcomps with the same LONGNAME corrections.

Thanks @zhaobin74!!

**Comment by gmao-rreichle** [comment]
Marking this "ready for review" - still needs approval from the following teams:
@GEOS-ESM/land-team : @mathomp4 or @rdkoster)
@GEOS-ESM/seaice-team : @mathomp4, @sanAkel, or @zhaobin74 
@GEOS-ESM/landice-team : @mathomp4, @zhaobin74, or @lcandre2

**Review by zhaobin74 — APPROVED** [review]

**Review by yvikhlya — APPROVED** [review]

**Comment by mathomp4** [comment]
@gmao-rreichle Let me know if you'd like me to approve for @GEOS-ESM/land-team. I usually hold off as the approver of last resort only because my concern is usually "It builds, ship it!" I figure @rdkoster might be a bit more nuanced. 😄

**Pull request merged**
