### PR TITLE
Feature/yury/s2s3 merge

### LINKED ISSUE #85: Merge S2S3 tag from CVS into develop branch
This includes dual ocean code, update to precip correction and additional coupled diagnostics. This also involves updates in GEOSgcm_App and GMAO_Shared repositories.

### PR DESCRIPTION
**Pull request by yvikhlya**
Fixes #85. This branch should be tested together with feature/yury/s2s3-merge in GEOSgcm_App and GMAO_Shared repositories.

### CODE REVIEW

**Comment by sdrabenh** [comment]
@JustinPerket do any of these changes to surface adversely affect you?

**Comment by sdrabenh** [comment]
@wmputman I have verified these changes are zero-diff. Are these update ok with you?

**Comment by JustinPerket** [comment]
> @JustinPerket do any of these changes to surface adversely affect you?

The precip correction changes come from my cvs tag `JU_WMP_PTYPE_PCSCALE`, but we never assessed the impacts. This would affect land using corrected precip. @gmao-rreichle can correct me, but I think we need to assess if this does in fact improve precip partitioning in LDAS

**Comment by JustinPerket** [comment]
> The precip correction changes come from my cvs tag `JU_WMP_PTYPE_PCSCALE`, but we never assessed the impacts. This would affect land using corrected precip. @gmao-rreichle can correct me, but I think we need to assess if this does in fact improve precip partitioning in LDAS

Alternatively, if s2s efforts can not wait for our validation, we could wrap the new precip correction method in a switch and preserve the old way.

**Comment by yvikhlya** [comment]
> > The precip correction changes come from my cvs tag `JU_WMP_PTYPE_PCSCALE`, but we never assessed the impacts. This would affect land using corrected precip. @gmao-rreichle can correct me, but I think we need to assess if this does in fact improve precip partitioning in LDAS
> 
> Alternatively, if s2s efforts can not wait for our validation, we could wrap the new precip correction method in a switch and preserve the old way.

S2S is based on Icarus-3.3. If you are not ready to accept new precip correction in Jason, we could just revert to old one for now.

**Comment by gmao-rreichle** [comment]
@JustinPerket, @yvikhlya, @sdrabenh 
re. the precip correction changes:
From what I can tell this would not affect LDAS or SMAP because in off-line (land-only) mode the corrected precip is simply read from a file. 
The only system we are currently running with precip corrections is MERRA-2, which is frozen anyway.
No objections on this merger from my end.

**Comment by gmao-rreichle** [comment]
I guess this leaves the question of who has done or still needs to do testing of the revised precip corrections.  Has this been tested by the S2S group?

**Comment by yvikhlya** [comment]
> I guess this leaves the question of who has done or still needs to do testing of the revised precip corrections. Has this been tested by the S2S group?

I did a  [coupled replay run](https://gmao.gsfc.nasa.gov/intranet/research/modeling/agcm/geos5/ic33p2-do4/) with new precip correction and we are satisfied with what it is doing. Eric is currently testing it in ODAS mode.

**Comment by JustinPerket** [comment]
>The only system we are currently running with precip corrections is MERRA-2, which is frozen anyway.
No objections on this merger from my end.

> I did a coupled replay run with new precip correction and we are satisfied with what it is doing. Eric is currently testing it in ODAS mode.

It looks like there are no objections then

**Comment by wmputman** [comment]
If @yvikhlya and @gmao-rreichle are satisfied and @sdrabenh has confirmed zero-diff then I am fine with this.

**Pull request merged**
