### PR TITLE
Add option to read ocean _data_ using `ExtData`

### PR DESCRIPTION
**Pull request by sanAkel**
This PR adds an **optional** capability to read in ocean boundary conditions:
- From netcdf formatted files, currently only binary formatted files are supported. The netcdf files are read via `ExtData`.
- This PR retains the current binary inputs as **default**, whereas the netcdf inputs are **optional**, turned `ON` by setting: `OCEAN_EXT_DATA:.TRUE` in `AGCM.rc`, in which case the user is expected to provide an `.rc` file with the correct format (see below for an **example**).

Reg. input netcdf files:
   - In `coupled` configuration one needs to provide ocean color (KPAR) only (without using `OBIO`, with `DO_OBIO=0`).
   - In `uncoupled` configuration we need KPAR, SST and sea ice concentration.
   - Support for ⬆️ is provided via https://github.com/GEOS-ESM/GMAO_Shared/pull/245

The changes in this PR are **zero-diff in default mode (binary inputs)**, and for the netcdf inputs, the differences are within the expected range (accounting for differences in ExtData and MAP_ReadForcing, as per @bena-nasa). This was checked in:
- [x] uncoupled mode.
- [x] coupled mode.

**Example** `.rc` file:

```
PrimaryExports%%
# -------------|-------|-------|--------|----------------------|--------|--------|-------------|----------|
#  Import      |       |       | Regrid |        Refresh       | OffSet | Scale  | Variable On |   File   |
#  Name        | Units | Clim  | Method |     Time Template    | Factor | Factor |     File    | Template |
# -------------|-------|-------|--------|----------------------|--------|--------|-------------|----------|

DATA_ICE         '1'    N         N               0               none   none FRSEAICE /discover/nobackup/sakella/extData_uncoupled/scratch_orig/extData_uncoupled.geosgcm_surf.%y4%m2%d2_%h230z.nc4
DATA_SST         'K'    N         N               0               none   none TS       /discover/nobackup/sakella/extData_uncoupled/scratch_orig/extData_uncoupled.geosgcm_surf.%y4%m2%d2_%h230z.nc4
DATA_KPAR        'm-1'  Y         N               0               none   none KPAR     /discover/nobackup/sakella/BCs/test_ocean_ext/prepare_ocnExtData/clim_kpar_GMAO2022.nc4
%%
```

### CODE REVIEW

**Comment by sanAkel** [comment]
@sdrabenh please consider merging **this** PR **BEFORE** https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/551
🙇‍♂️

**Review by bena-nasa — DISMISSED** [review]

**Review by yvikhlya — DISMISSED** [review]

**Comment by sdrabenh** [comment]
@mathomp4 it looks like gfortran is complaining about a type cast. @sanAkel would you mind fixing so both compilers are happy? Thanks

**Comment by mathomp4** [comment]
> @mathomp4 it looks like gfortran is complaining about a type cast. @sanAkel would you mind fixing so both compilers are happy? Thanks

I can fix it. it's something I recognize.

**Comment by sanAkel** [comment]
@mathomp4 🙏 for the quick fix

**Review by yvikhlya — APPROVED** [review]

**Comment by sdrabenh** [comment]
@mathomp4 thanks! I don't know how you spot these things so easily

**Comment by sanAkel** [comment]
> @mathomp4 thanks! I don't know how you spot these things so easily

yeah! Especially those spaces: " " 😮

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
