### PR TITLE
Merging refactored physics code into develop

### PR DESCRIPTION
**Pull request by sdrabenh**

### CODE REVIEW

**Comment by gmao-rreichle** [comment]
@biljanaorescanin, please run the GEOSldas test suite with this GEOSgcm_GridComp branch and the related GMAO_Shared PR https://github.com/GEOS-ESM/GMAO_Shared/pull/321 and possibly others that I'm missing.  With any luck, one set of LDAS tests that exercises all of these PRs simultaneously will do the trick.

**Comment by sdrabenh** [comment]
> @biljanaorescanin, please run the GEOSldas test suite with this GEOSgcm_GridComp branch and the related GMAO_Shared PR [GEOS-ESM/GMAO_Shared#321](https://github.com/GEOS-ESM/GMAO_Shared/pull/321) and possibly others that I'm missing. With any luck, one set of LDAS tests that exercises all of these PRs simultaneously will do the trick.

@gmao-rreichle @biljanaorescanin things are still in a bit of flux as we try to figure out any issues. This is what we are currently looking to update:
`mepo compare
Repo                   | Original             | Current
---------------------- | -------------------- | -------
GEOSgcm                | (t) v10.25.1 (DH)    | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
cmake                  | (t) v3.26.0 (DH)     | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
GMAO_Shared            | (t) v1.7.2 (DH)      | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
GEOS_Util              | (t) v1.0.2 (DH)      | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
GEOSgcm_GridComp       | (t) v1.17.4 (DH)     | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
FVdycoreCubed_GridComp | (t) v1.12.1 (DH)     | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
fvdycore               | (t) geos/v1.5.0 (DH) | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
GOCART                 | (t) v2.1.2 (DH)      | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
GEOSradiation_GridComp | (t) v1.2.0 (DH)      | (b) feature/sdrabenh/merge_v10.25.1_MSTRF
GEOSgcm_App            | (t) v1.9.4 (DH)      | (b) feature/sdrabenh/merge_v10.25.1_MSTRF`

**Comment by gmao-rreichle** [comment]
> @gmao-rreichle @biljanaorescanin things are still in a bit of flux as we try to figure out any issues. This is what we are currently looking to update: `mepo compare

Thanks, @sdrabenh.  Please let us know when it makes sense to run the GEOSldas tests.

**Review by mathomp4 — APPROVED** [review]

**Comment by gmao-rreichle** [comment]
> Thanks, @sdrabenh. Please let us know when it makes sense to run the GEOSldas tests.

@sdrabenh, @mathomp4: I was surprised this was merged without LDAS approval.  When I first saw the PR, I didn't have time to go through in detail and asked @biljanaorescanin to test, to be safe.  After taking a closer look just now, the changes in Surface GC seem innocuous enough, so it should be 0-diff for the LDAS tests.  There is, however, also a minor edit in `mk_restarts`.  You may remember that @weiyuan-jiang added a python version of mk_restarts which may need updating accordingly.  We shouldn't forget about this and we should, in any case, start deprecating `mk_restarts`.  @weiyuan-jiang, please take a look at the change in mk_restarts and make a similar change in the python code (if warranted).

**Comment by gmao-rreichle** [comment]
@sdrabenh: GEOSldas is now using tags for GEOS_Util and GMAO_Shared, but GEOSldas will **NEVER** use tags for GEOSgcm_GridComp, so there's no way you could push to GCM GC develop without impacting LDAS.  Using a GCM GC tag in LDAS would defeat the purpose of coordinated atm and land model development.  FWIW, though, I think the moist physics refactoring stuff is sufficiently orthogonal to LDAS that tonight's LDAS tests will not blow up.  We only have to remember to update the python version of mk_restarts.

**Comment by sanAkel** [comment]
> @sdrabenh: GEOSldas is now using tags for GEOS_Util and GMAO_Shared, but GEOSldas will **NEVER** use tags for GEOSgcm_GridComp, so there's no way you could push to GCM GC develop without impacting LDAS. Using a GCM GC tag in LDAS would defeat the purpose of coordinated atm and land model development. FWIW, though, I think the moist physics refactoring stuff is sufficiently orthogonal to LDAS that tonight's LDAS tests will not blow up. We only have to remember to update the python version of mk_restarts.

@sdrabenh I have **same** concerns and questions as :arrow_up. I am opposed to this merge.

**Pull request merged**
