### PR TITLE
enable C-EVP in CICE6 

### PR DESCRIPTION
**Pull request by zhaobin74**
This PR adds support for **C-EVP** in ```CICE6``` by importing C-grid currents from ```MOM6``` into ```CICE_Plug```.

Additionally a new utility to convert ```CICE4``` thermo restarts into ```CICE6``` native format was added.

Depends on https://github.com/GEOS-ESM/CICE/pull/2
Depends on updated [MOM6](https://github.com/GEOS-ESM/MOM6) and [GEOS_OceanGridComp](https://github.com/GEOS-ESM/GEOS_OceanGridComp)

### CODE REVIEW

**Review by yvikhlya — APPROVED** [review]

**Comment by zhaobin74** [comment]
Convert to draft for now until [MOM6](https://github.com/GEOS-ESM/MOM6) and [GEOS_OceanGridComp](https://github.com/GEOS-ESM/GEOS_OceanGridComp) are pulled in.

**Comment by mathomp4** [comment]
New ocean is in GEOS. So I've pressed update branch to see what happens

**Comment by mathomp4** [comment]
Hooray. All runs!

**Comment by zhaobin74** [comment]
Thanks, @mathomp4. It can proceed now. May need another merge with develop.

**Review by mathomp4 — APPROVED** [review]

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
