### PR TITLE
Introducing the GF version 2020

### PR DESCRIPTION
**Pull request by srfreita**
This a new version that I am planning to be the base of the GF scheme in GEOS-5 onwards. The code was clean up; the three convective modes now have a unified treatment, contains several new physical and improved numerical aspects. It also has the "cold-pool" parameterization developed several months ago, including a 'convective memory' capability. Lastly, it also contains a lightning parameterization (Lopez, 2016 MWR), in-line with the deep convection module.
The convective tracer transport and wet removal modules were not touched. 
Using the default configuration, it presents zero-diff with the "develop" tag.

### CODE REVIEW

**Comment by wmputman** [comment]
@sdrabenh can we verify that these changes are zero-diff to the latest develop?

**Comment by sdrabenh** [comment]
> @sdrabenh can we verify that these changes are zero-diff to the latest develop?

@wmputman absolutely. I will test this PR tonight

**Comment by mathomp4** [comment]
This might be the largest-difference commit I've ever seen. Well-earned applause! 👏

**Comment by sdrabenh** [comment]
@srfreita and @wmputman I ran my 1-day C48 tests on this and it looks like this PR is NOT 0-diff. Here is the breakdown:
1) develop amip vs PR amip: all 20 checkpoints differ
2) develop replay vs PR replay: all 20 checkpoints differ
3) PR amip vs PR 0-inc replay: all 20 checkpoints pass
4) My regression tests failed because I ran out of wallclock time - I will check later

Many differences are significant - not just round off errors. Please feel free to look at the files between the 2 experiments, "develop" and "pullreq" at:
`/discover/nobackup/projects/gmao/g6dev/sdrabenh/ZeroDiffTests/PR_GF-2020/`

For example, from the above directory issue the command:
`cdo -diffn develop/scratch.1day_amip.dev/fvcore_internal_checkpoint pullreq/scratch.1day_amip.pul/fvcore_internal_checkpoint`

**Comment by srfreita** [comment]
Hi Scott,
Thanks for checking that. I only verified the 'geosgcm_prog' collection. I did it again using the "cdo" command, and those files are zero-diff:

/discover/nobackup/srfreita/geos5/x_zero_diff>cdo -diffn  new.holding/geosgcm_prog/201801/new.geosgcm_prog.20180101_0900z.nc4 tag.holding/geosgcm_prog/201801/tag.geosgcm_prog.20180101_0900z.nc4
**cdo.exe diffn: Processed 2016262080 values from 82 variables over 2 timesteps ( 58.23s )**

Saulo

**Comment by srfreita** [comment]
Hi Scott,
Thanks for checking that. I only verified the 'geosgcm_prog' collection. I did it again using the "cdo" command, and those files are zero-diff:
/discover/nobackup/srfreita/geos5/x_zero_diff>cdo -diffn new.holding/geosgcm_prog/201801/new.geosgcm_prog.20180101_0900z.nc4 tag.holding/geosgcm_prog/201801/tag.geosgcm_prog.20180101_0900z.nc4
cdo.exe diffn: Processed 2016262080 values from 82 variables over 2 timesteps ( 58.23s )
Saulo

**Comment by sdrabenh** [comment]
@srfreita that is the peculiar part to me. Yes, my 'geosgcm_prog' was 0-diff too, but many history collections are time averaged. I am looking that all checkpoint/restart files are identical.

**Comment by mathomp4** [comment]
Note if you like to have a bit of statistics, you can use `nccmp` as well. Looking at fvcore, the differences are:
```(1002) $ nccmp -dqfSB develop/scratch.1day_amip.dev/fvcore_internal_checkpoint pullreq/scratch.1day_amip.pul/fvcore_internal_checkpoint
Variable Group  Count      Sum      AbsSum         Min        Max     Range         Mean      StdDev
PE       /     988771 -25443.8 1.05188e+06    -68.8452    71.0404   139.886   -0.0257328     2.74037
PKZ      /     986729 -2.18554      94.871 -0.00577329 0.00559028 0.0113636 -2.21494e-06 0.000238932
PT       /     995327 -78.7735     7746.27    -6.32273    3.46943   9.79216 -7.91434e-05   0.0232624
U        /     995328  672.561     79769.8    -7.60102    7.71399    15.315  0.000675718    0.138249
V        /     995328 -1079.04     78643.4    -5.70421    6.17811   11.8823  -0.00108411    0.133763
```
Using a relative tolerance of 1% shows that PT, U, and V, are pretty different:
```
(1003) $ nccmp -dqfSB -T 1.0 develop/scratch.1day_amip.dev/fvcore_internal_checkpoint pullreq/scratch.1day_amip.pul/fvcore_internal_checkpoint
Variable Group  Count      Sum  AbsSum      Min     Max   Range        Mean   StdDev
PT       /         76 -14.5361 95.0545 -6.32273 3.46943 9.79216   -0.191264  1.63636
U        /     409797  426.681 54063.3 -7.60102 7.71399  15.315   0.0010412  0.19998
V        /     421934 -830.094 54014.4 -5.70421 6.17811 11.8823 -0.00196736 0.191165
```

**Comment by srfreita** [comment]
@sdrabenh did the regression test finish?

**Comment by wmputman** [comment]
@srfreita , until this passes zero-diff tests and regression we cannot move forward with the review

**Comment by srfreita** [comment]
It also did not pass regression?

**Comment by srfreita** [comment]
@sdrabenh can you confirm this request this tag did not pass regression?

**Comment by sdrabenh** [comment]
@srfreita and @wmputman I confirmed this did pass the regression testing. The problem was the restarts.

**Comment by mathomp4** [comment]
@wmputman Should we close this in favor of the edits you have in development?

**Pull request closed without merging**
