### PR TITLE
Bugfix/narnold1/#201 scm fixes

### PR DESCRIPTION
**Pull request by narnold1**
Correcting issues with the single column model. (1) GF imports from DYN are not filled; (2) scm_setup incompletely adjusts for L132; (3) SST file for cfmip_s11 case is incorrect.

See branch bugfix/narnold1/#201-scm-fixes in GEOSgcm_GridComp and GEOSgcm_App repos.

### CODE REVIEW

**Comment by narnold1** [comment]
This is non-0-diff for single column, but trivially 0-diff for any global application.

**Comment by mathomp4** [comment]
@narnold1 I don't see any PR in the GEOSgcm_App directory. Were those fixes already taken?

**Comment by narnold1** [comment]
@mathomp4  I just added the PR for GEOSgcm_App.

**Comment by mathomp4** [comment]
> @mathomp4 I just added the PR for GEOSgcm_App.

Ah 😄 

I think you once said you had a fix to one of the cases in the SCM as well, right?

**Comment by narnold1** [comment]
I have a fix for the sst.data file for the "cfmip-s11" case.  New file is:  /discover/nobackup/narnold1/tests/scm_s11/dev_shoc_L132/sst292p45.data

It should be renamed to sst.data

**Comment by mathomp4** [comment]
> I have a fix for the sst.data file for the "cfmip-s11" case. New file is: /discover/nobackup/narnold1/tests/scm_s11/dev_shoc_L132/sst292p45.data
> 
> It should be renamed to sst.data

Okay. Once your changes go in, I'll (try to remember to) change this. Ping me if I forget. That way at least it's "hidden" in a non-zero-diff change to the SCM.

**Pull request merged**
